---
# group vars file for lb(load balancer) servers
nginx_server_name: 'web.example.com'
nginx_proxy_backends: ['app1:5000', 'app2:5000']
nginx_cluster_info: {virtual_ipaddr: '{{ lb_vip }}', check_interface: 'eth1'}
