---
- name: certificate deploy
  hosts: lbservers
  vars:
    now_date: "{{ lookup('pipe','date +%Y%m%d') }}"
    server_process: haproxy
    cert_directory: /etc/haproxy/cert
    cert_files:
        - server.pem
  tasks:
    - name: create cert directory
      file:
        path: '{{ cert_directory }}'
        state: directory
        mode: '0755'
    - name: upload cert files
      copy:
        src: 'files/{{ item }}'
        dest: '{{ cert_directory }}/{{ now_date }}_{{ item }}'
        mode: '0644'
      with_items: '{{ cert_files }}'
    - name: deploy certificate
      file:
        src: '{{ cert_directory }}/{{ now_date }}_{{ item }}'
        dest: '{{ cert_directory }}/{{ item }}'
        state: link
        force: yes
      with_items: '{{ cert_files }}'
      notify: 'reload {{ server_process }} service'
  handlers:
    - name: 'reload {{ server_process }} service'
      service:
        name: '{{ server_process }}'
        state: reloaded
