---
- name: certificate deploy
  hosts: lbservers
  become: true
  vars:
    now_date: "{{ lookup('pipe','date +%Y%m%d') }}"
    cert_files:
        - server.pem
  pre_tasks:
    - name: detect haproxy service
      stat:
        path: /etc/haproxy
      register: haproxy_service
  tasks:
    - name: create directory
      file:
        path: /etc/haproxy/cert
        state: directory
        mode: '0755'
    - name: upload cert files
      copy:
        src: 'files/{{ item }}'
        dest: '/etc/haproxy/cert/{{ now_date }}_{{ item }}'
        mode: '0644'
      with_items: '{{ cert_files }}'
    - name: deploy certificate
      file:
        src: '/etc/haproxy/cert/{{ now_date }}_{{ item }}'
        dest: '/etc/haproxy/cert/{{ item }}'
        state: link
      with_items: '{{ cert_files }}'
      notify: reload haproxy service
  handlers:
    - name: reload haproxy service
      service:
        name: haproxy
        state: reloaded
      when: haproxy_service.stat.exists
