---
- name: deploy database servers
  hosts: rdbservers
  roles:
    - role: ansible-role-pacemaker
      tags: pacemaker
      when: ansible_play_hosts | length > 1
    - role: ansible-role-postgresql
      tags: postgresql
