---
- src: https://github.com/izumimatsuo/ansible-role-docker
- src: https://github.com/izumimatsuo/ansible-role-haproxy
- src: https://github.com/izumimatsuo/ansible-role-osinit
- src: https://github.com/izumimatsuo/ansible-role-postgresql
- src: https://github.com/izumimatsuo/ansible-role-stretcher
